import type { SwitchCatalogEntry } from './types'

/**
 * Hardcoded Aruba CX data-center switch catalog. Port counts/speeds are
 * representative of commonly deployed SKUs per series, not an exhaustive
 * list of every part number. VSX/EVPN support reflects current AOS-CX
 * capability per series — verify against the target firmware release.
 */
export const SWITCH_CATALOG: SwitchCatalogEntry[] = [
  {
    id: 'aruba-8320-48y6c',
    vendor: 'Aruba',
    series: 'CX 8320',
    model: '8320-48Y6C',
    suitableRoles: ['leaf', 'border'],
    portGroups: [
      { count: 48, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 },
      { count: 6, speedGbps: 100, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: '48x 1/10/25G SFP28 downlinks + 6x 40/100G QSFP28 uplinks. Common ToR leaf.',
  },
  {
    id: 'aruba-8325-32c',
    vendor: 'Aruba',
    series: 'CX 8325',
    model: '8325-32C',
    suitableRoles: ['spine', 'leaf'],
    portGroups: [{ count: 32, speedGbps: 100, namePrefix: '1/1/', startIndex: 1 }],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: '32x 40/100G QSFP28, high port-density — typical EVPN fabric spine.',
  },
  {
    id: 'aruba-8325-32c-breakout',
    vendor: 'Aruba',
    series: 'CX 8325',
    model: '8325-32C (4x25G breakout)',
    suitableRoles: ['leaf'],
    portGroups: [{ count: 128, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 }],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: 'Same physical switch as 8325-32C with every 100G QSFP28 port broken out 4x25G via breakout cable — high-density leaf downlinks. Port numbering here is simplified sequential (1/1/1-128); real AOS-CX breakout ports are numbered n:1-n:4 per parent port.',
  },
  {
    id: 'aruba-8325-48y8c',
    vendor: 'Aruba',
    series: 'CX 8325',
    model: '8325-48Y8C',
    suitableRoles: ['leaf', 'spine'],
    portGroups: [
      { count: 48, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 },
      { count: 8, speedGbps: 100, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: '48x 1/10/25G SFP28 + 8x 40/100G QSFP28. Common VSX-paired leaf.',
  },
  {
    id: 'aruba-8325h-18y4c',
    vendor: 'Aruba',
    series: 'CX 8325H',
    model: '8325H-18Y4C',
    suitableRoles: ['leaf', 'spine'],
    portGroups: [
      { count: 18, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 100, namePrefix: '1/1/', startIndex: 19 },
    ],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: 'Half-width 1U, fixed (non-redundant-slot) power/fans. 18x 1/10/25G SFP28 (any combination, no port grouping) + 4x 40/100G QSFP28 uplinks, breakout-capable. Storage/HCI/edge-oriented ToR leaf.',
  },
  {
    id: 'aruba-8325h-16c',
    vendor: 'Aruba',
    series: 'CX 8325H',
    model: '8325H-16C',
    suitableRoles: ['spine', 'leaf'],
    portGroups: [{ count: 16, speedGbps: 100, namePrefix: '1/1/', startIndex: 1 }],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: 'Half-width 1U, fixed power/fans. 16x 40/100G QSFP28, each breakout-capable to 4x25G. Compact high-density spine/leaf for edge or colocation sites.',
  },
  {
    id: 'aruba-8360-24xf4c',
    vendor: 'Aruba',
    series: 'CX 8360',
    model: '8360-24XF4C',
    suitableRoles: ['leaf'],
    portGroups: [
      { count: 24, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 100, namePrefix: '1/1/', startIndex: 25 },
    ],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: 'Fanless 24x 10/25G SFP28 + 4x 40/100G QSFP28. Smaller-footprint leaf.',
  },
  {
    id: 'aruba-8400-core',
    vendor: 'Aruba',
    series: 'CX 8400',
    model: '8400 (2x 24p 40/100G modules)',
    suitableRoles: ['spine', 'border'],
    portGroups: [{ count: 48, speedGbps: 100, namePrefix: '1/1/', startIndex: 1 }],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: 'Modular DC core chassis; port count shown assumes two 24-port 40/100G line cards. Actual slot/module config varies per deployment.',
  },
  {
    id: 'aruba-9300-32d',
    vendor: 'Aruba',
    series: 'CX 9300',
    model: '9300-32D',
    suitableRoles: ['spine'],
    portGroups: [{ count: 32, speedGbps: 400, namePrefix: '1/1/', startIndex: 1 }],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: '32x 400G QSFP-DD, highest density spine option for large EVPN fabrics.',
  },
  {
    id: 'aruba-9300-48y4c',
    vendor: 'Aruba',
    series: 'CX 9300',
    model: '9300-48Y4C',
    suitableRoles: ['leaf', 'spine'],
    portGroups: [
      { count: 48, speedGbps: 25, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 100, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: true,
    maxVlans: 4094,
    notes: '48x 1/10/25G SFP56 + 4x 100G QSFP28 uplinks. Latest-generation leaf.',
  },

  // ---- Access-layer switches: not VXLAN VTEPs, just uplink into the fabric ----
  {
    id: 'aruba-6200f-24g',
    vendor: 'Aruba',
    series: 'CX 6200',
    model: '6200F 24G 4SFP+',
    suitableRoles: ['access'],
    portGroups: [
      { count: 24, speedGbps: 1, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 10, namePrefix: '1/1/', startIndex: 25 },
    ],
    supportsVsx: false,
    supportsEvpn: false,
    maxVlans: 1024,
    notes: 'Fixed L2/L3-lite access switch, 24x 1G copper + 4x 1/10G SFP+ uplinks. Not a VXLAN VTEP — terminates end hosts and uplinks into the fabric.',
  },
  {
    id: 'aruba-6200f-48g',
    vendor: 'Aruba',
    series: 'CX 6200',
    model: '6200F 48G 4SFP+',
    suitableRoles: ['access'],
    portGroups: [
      { count: 48, speedGbps: 1, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 10, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: false,
    supportsEvpn: false,
    maxVlans: 1024,
    notes: 'Fixed L2/L3-lite access switch, 48x 1G copper + 4x 1/10G SFP+ uplinks. Not a VXLAN VTEP — terminates end hosts and uplinks into the fabric.',
  },
  {
    id: 'aruba-6300m-24g',
    vendor: 'Aruba',
    series: 'CX 6300',
    model: '6300M 24G 4SFP56',
    suitableRoles: ['access'],
    portGroups: [
      { count: 24, speedGbps: 10, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 40, namePrefix: '1/1/', startIndex: 25 },
    ],
    supportsVsx: true,
    supportsEvpn: false,
    maxVlans: 4094,
    notes: 'Campus access/aggregation switch, 24x 1/10G + 4x 25/50G SFP56 uplinks (shown at 40G). Supports VSX for dual-homed uplinks but is not a VXLAN VTEP in this tool.',
  },
  {
    id: 'aruba-6300m-48g',
    vendor: 'Aruba',
    series: 'CX 6300',
    model: '6300M 48G 4SFP56',
    suitableRoles: ['access'],
    portGroups: [
      { count: 48, speedGbps: 1, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 40, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: false,
    maxVlans: 4094,
    notes: 'Campus access/aggregation switch, 48x 1G copper + 4x 25/50G SFP56 uplinks (shown at 40G). Supports VSX for dual-homed uplinks but is not a VXLAN VTEP in this tool.',
  },
  {
    id: 'aruba-6300m-24sfp',
    vendor: 'Aruba',
    series: 'CX 6300',
    model: '6300M 24SFP+ 4SFP56',
    suitableRoles: ['access'],
    portGroups: [
      { count: 24, speedGbps: 10, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 40, namePrefix: '1/1/', startIndex: 25 },
    ],
    supportsVsx: true,
    supportsEvpn: false,
    maxVlans: 4094,
    notes: 'All-fiber campus access/aggregation switch, 24x 1/10G SFP+ downlinks + 4x 25/50G SFP56 uplinks (shown at 40G). Supports VSX for dual-homed uplinks but is not a VXLAN VTEP in this tool.',
  },
  {
    id: 'aruba-6300m-48sfp',
    vendor: 'Aruba',
    series: 'CX 6300',
    model: '6300M 48SFP+ 4SFP56',
    suitableRoles: ['access'],
    portGroups: [
      { count: 48, speedGbps: 10, namePrefix: '1/1/', startIndex: 1 },
      { count: 4, speedGbps: 40, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: false,
    maxVlans: 4094,
    notes: 'All-fiber campus access/aggregation switch, 48x 1/10G SFP+ downlinks + 4x 25/50G SFP56 uplinks (shown at 40G). Supports VSX for dual-homed uplinks but is not a VXLAN VTEP in this tool.',
  },
  {
    id: 'aruba-8100-40xt-8sfp-4qsfp',
    vendor: 'Aruba',
    series: 'CX 8100',
    model: '8100 40XT 8SFP+ 4QSFP28',
    suitableRoles: ['access'],
    portGroups: [
      { count: 40, speedGbps: 10, namePrefix: '1/1/', startIndex: 1 },
      { count: 8, speedGbps: 10, namePrefix: '1/1/', startIndex: 41 },
      { count: 4, speedGbps: 100, namePrefix: '1/1/', startIndex: 49 },
    ],
    supportsVsx: true,
    supportsEvpn: false,
    maxVlans: 4094,
    notes: '40x 100M/1/2.5/5/10G BASE-T copper + 8x 1/10G SFP+ + 4x 40/100G QSFP28 uplinks (shown at 100G). High fabric-uplink bandwidth access/aggregation switch. Supports VSX for dual-homed uplinks but is not a VXLAN VTEP in this tool — verify VSX support against your target firmware.',
  },
]

/** Looks up a catalog entry by id — the shipped, verified catalog first, then any project-local custom entries (e.g. synthesized from a Visio import). */
export function getCatalogEntry(id: string, customEntries: SwitchCatalogEntry[] = []): SwitchCatalogEntry | undefined {
  return SWITCH_CATALOG.find((c) => c.id === id) ?? customEntries.find((c) => c.id === id)
}

/** The full catalog available to a project: shipped entries plus any project-local custom ones. */
export function allCatalogEntries(customEntries: SwitchCatalogEntry[] = []): SwitchCatalogEntry[] {
  return [...SWITCH_CATALOG, ...customEntries]
}
